apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    aadpodidbinding: my-pod-identity
  namespace: my-app
spec:
  containers:
  - name: demo
    image: mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.6.3
    args:
      - --subscriptionid=7b8ab5b5-0b57-470b-b81b-36f3d35c159a
      - --clientid=d70942b1-9b2d-4baa-bc44-125cc6343e52
      - --resourcegroup=myIdentityResourceGroup
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  nodeSelector:
    kubernetes.io/os: linux