apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: api
spec:
  type: LoadBalancer
  selector:
    tier: demo
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
