apiVersion: v1
kind: Pod
metadata:
  name: poi
  labels:
    tier: poi
  namespace: api 
spec:
  containers:
  - name: poi
    image: registrygzx5650.azurecr.io/poi:1.0    
    env:        
    - name: SQL_SERVER
      value: sqlservergzx5650.database.windows.net
    volumeMounts:
    - name: vm-secrets-hacker05
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
  - name: vm-secrets-hacker05
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "oh5kv"
