# This is a SecretProviderClass example using system-assigned identity to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: oh5kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: "771472e8-8920-47d2-a64b-7448a4be2ecd"      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: keyvault-hacker5
    objects:  |
      array:
        - |
          objectName: SQLPASSWORD
          objectType: secret        # object types: secret, key or cert
          objectVersion: "d956b386b92f4d5780167bf76c5d34a3"         # [OPTIONAL] object versions, default to latest if empty
          objectAlias: SQL_PASSWORD
        - |
          objectName: SQLUSER
          objectType: secret
          objectVersion: "accbd5df312f4c41b42ac06aa935ead6"
          objectAlias: SQL_USER
    tenantId: "a8315874-5df5-41ef-9776-eda87ce523c9"           # The tenant ID of the Azure Key Vault instance