apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    tier: tripviewer
  name: tripinsights/tripviewer
spec:
  containers:
  - image: registrygzx5650.azurecr.io/tripinsights/tripviewer
    name: tripinsights/tripviewer
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
