apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: web
spec:
  type: LoadBalancer
  selector:
    tier: tripviewer
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
