apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: trips
  name: trips
  namespace: api
spec:
  containers:
    - image: registrygzx5650.azurecr.io/trips:1.0
      name: trips
      env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: SQL_PASSWORD
        - name: SQL_SERVER
          value: sqlservergzx5650.database.windows.net
        - name: OPENAPI_DOCS_URI
          value: http://localhost
