apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    tier: trips
  name: trips
spec:
  containers:
  - image: registrygzx5650.azurecr.io/trips
    name: trips
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
