apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: tripviewer
  name: tripviewer
spec:
  containers:
    - image: registrygzx5650.azurecr.io/tripinsights/tripviewer:1.0
      name: tripviewer
      env:
        - name: USERPROFILE_API_ENDPOINT
          value: http://userprofile-service
        - name: TRIPS_API_ENDPOINT
          value: http://trips-service

