apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    tier: user-java
  name: user-java
  namespace: api
spec:
  containers:
  - image: registrygzx5650.azurecr.io/user-java:1.0
    name: user-java
    env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: SQL_PASSWORD
        - name: SQL_SERVER
          value: sqlservergzx5650.database.windows.net
