# This is a SecretProviderClass example using system-assigned identity to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo01kv
  namespace: web
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: "e9dbb3fe-8c68-4409-8f73-76c1c13d3488"      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "decisielkeyvaultstaging "
    objects:  |
      array:
        - |
          objectAlias: demo
          objectName: demo
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectAlias: cert-demo
          objectName: cert-demo
          objectType: cert
          objectVersion: ""
    resourceGroup: "rg-demo01"                      
    subscriptionId: "6b4a1f9a-b1f2-4afd-9339-5bf070f38d65" 
    tenantId: "f2b96945-e59f-42b1-a787-cf144f8f872e"         # The tenant ID of the Azure Key Vault instance   
  secretObjects:
    - secretName: demo
      data:
      - key: demo
        objectName: demo
      type: Opaque
    - secretName: cert-demo
      data:
      - key: cert-demo
        objectName: cert-demo
      type: Opaque      
    
